//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISET2018_WebServicesUtilisation.UtiliserServiceHEL {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/ISET2018_WebServices")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WS_Personne", Namespace="http://schemas.datacontract.org/2004/07/ISET2018_WebServices")]
    [System.SerializableAttribute()]
    public partial class WS_Personne : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenomField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenom {
            get {
                return this.PrenomField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenomField, value) != true)) {
                    this.PrenomField = value;
                    this.RaisePropertyChanged("Prenom");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UtiliserServiceHEL.IServiceHEL")]
    public interface IServiceHEL {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHEL/HelloWorld", ReplyAction="http://tempuri.org/IServiceHEL/HelloWorldResponse")]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHEL/HelloWorld", ReplyAction="http://tempuri.org/IServiceHEL/HelloWorldResponse")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHEL/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceHEL/GetDataUsingDataContractResponse")]
        ISET2018_WebServicesUtilisation.UtiliserServiceHEL.CompositeType GetDataUsingDataContract(ISET2018_WebServicesUtilisation.UtiliserServiceHEL.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHEL/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceHEL/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ISET2018_WebServicesUtilisation.UtiliserServiceHEL.CompositeType> GetDataUsingDataContractAsync(ISET2018_WebServicesUtilisation.UtiliserServiceHEL.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHEL/GetPersonneByID", ReplyAction="http://tempuri.org/IServiceHEL/GetPersonneByIDResponse")]
        ISET2018_WebServicesUtilisation.UtiliserServiceHEL.WS_Personne GetPersonneByID(int nID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHEL/GetPersonneByID", ReplyAction="http://tempuri.org/IServiceHEL/GetPersonneByIDResponse")]
        System.Threading.Tasks.Task<ISET2018_WebServicesUtilisation.UtiliserServiceHEL.WS_Personne> GetPersonneByIDAsync(int nID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceHELChannel : ISET2018_WebServicesUtilisation.UtiliserServiceHEL.IServiceHEL, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceHELClient : System.ServiceModel.ClientBase<ISET2018_WebServicesUtilisation.UtiliserServiceHEL.IServiceHEL>, ISET2018_WebServicesUtilisation.UtiliserServiceHEL.IServiceHEL {
        
        public ServiceHELClient() {
        }
        
        public ServiceHELClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceHELClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHELClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHELClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public ISET2018_WebServicesUtilisation.UtiliserServiceHEL.CompositeType GetDataUsingDataContract(ISET2018_WebServicesUtilisation.UtiliserServiceHEL.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ISET2018_WebServicesUtilisation.UtiliserServiceHEL.CompositeType> GetDataUsingDataContractAsync(ISET2018_WebServicesUtilisation.UtiliserServiceHEL.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public ISET2018_WebServicesUtilisation.UtiliserServiceHEL.WS_Personne GetPersonneByID(int nID) {
            return base.Channel.GetPersonneByID(nID);
        }
        
        public System.Threading.Tasks.Task<ISET2018_WebServicesUtilisation.UtiliserServiceHEL.WS_Personne> GetPersonneByIDAsync(int nID) {
            return base.Channel.GetPersonneByIDAsync(nID);
        }
    }
}
